Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -7,7 +7,7 @@ commands:
       # Add parameter here   
     steps:
       - run:
-          name: Delete S3 content
+          name: Delete S3 files
           when: on_fail
           command: |
             aws s3 rm s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
@@ -24,11 +24,9 @@ commands:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
       # Add parameter here 
-        
     steps:
       - restore_cache:
           key: backend-build
-
       - run:
           name: Revert migrations
           # Add when this will run
@@ -70,8 +68,6 @@ jobs:
       - image: circleci/node:13.8.0
     steps:
       - checkout
-      #- restore_cache:
-      #    keys: [backend-build]
       - run:
           name: Back-end build
           command: |
@@ -82,6 +78,19 @@ jobs:
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
+      - run:
+          name: Get compiled code 
+          command: |
+            mkdir /tmp/workspace/
+            cp ./backend/package.json /tmp/workspace/
+            cd backend/dist
+            tar -zcvf /tmp/workspace/backend.tar.gz ./
+            #tar -zcvf ./../../backend.tar.gz ./    #to be removed
+      - persist_to_workspace:
+          root: /tmp/workspace
+          paths:
+            - package.json
+            - backend.tar.gz
 
   test-frontend:
     docker:
@@ -124,9 +133,9 @@ jobs:
            cd frontend
            npm install
            # npm install oauth-sign@^0.9.0
-           # npm audit fix --audit-level=critical --force
-           npm audit fix --force
-           npm audit --audit-level=critical
+           npm audit fix --audit-level=critical --force
+           #npm audit fix --force
+           #npm audit --audit-level=critical
 
   scan-backend:
     docker:
@@ -138,12 +147,12 @@ jobs:
       - run:
           name: Back-end scan
           command: |
-           cd frontend
+           cd backend
            npm install
            # npm install oauth-sign@^0.9.0
-           # npm audit fix --audit-level=critical --force
-           npm audit fix --force
-           npm audit --audit-level=critical
+           npm audit fix --audit-level=critical --force
+           # npm audit fix --force
+           # npm audit --audit-level=critical
 
   deploy-infrastructure:
     docker:
@@ -211,9 +220,24 @@ jobs:
           name: Configure server
           command: |
             # Your code here
+            cd backend
+            echo ENVIRONMENT=production > ".env"
+            echo TYPEORM_CONNECTION=postgres >> ".env"
+            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> ".env"
+            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> ".env"
+            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> ".env"
+            echo NODE_ENV=production >> ".env"
+            echo TYPEORM_HOST=$TYPEORM_HOST >> ".env"
+            echo TYPEORM_PORT=$TYPEORM_PORT >> ".env"
+            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> ".env"
+            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> ".env"
+            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> ".env"
+            cd ..
             export ANSIBLE_HOST_KEY_CHECKING=False
             ansible-playbook -i ~/inventory.txt .circleci/ansible/configure-server.yml
             #exit 1
+      # Here's where you will add some code to rollback on failure  
+      - destroy-environment
 
   run-migrations:
     docker:
@@ -221,7 +245,9 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys: [run-migration]
+          keys: [backend-build]
+      - attach_workspace:
+          at: ~/
       - run:
           name: Run migrations
           command: |
@@ -230,8 +256,11 @@ jobs:
             npm install
             # Run and save the migration output
             npm run migrations > migrations_dump.txt
+            cat migrations_dump.txt
+            migration_succesful=$(cat migrations_dump.txt | grep -c "has been executed successfully")
+            if [ $migration_succesful > 0 ]; then exit 0; else exit 1; fi;
       - run:
-          name: Send migration results to memstash
+          name: Send migration results to KVDB
           command: |
             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
@@ -240,6 +269,9 @@ jobs:
             # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
             curl https://kvdb.io/7iKzLiSyAUUM15XfoKBFeh/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
             fi
+      # Here's where you will add some code to rollback on failure
+      - revert-migrations
+      - destroy-environment
 
   deploy-frontend:
     docker:
@@ -259,7 +291,9 @@ jobs:
       - run:
           name: Get backend url
           command: |
+            touch ".env"
             export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+            echo $BACKEND_IP
             export API_URL="http://${BACKEND_IP}:3030"
             echo "API_URL = ${API_URL}"
             echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
@@ -306,16 +340,75 @@ jobs:
             npm i
             npm run build
             cd ..
-            # Zip the directory
             tar -C backend -czvf artifact.tar.gz .
             cd .circleci/ansible
-            echo "Contents  of the inventory.txt file is -------"
             cat ~/inventory.txt
-            export ANSIBLE_HOST_KEY_CHECKING=False
+            #export ANSIBLE_HOST_KEY_CHECKING=False
             ansible-playbook -i ~/inventory.txt deploy-backend.yml
       # Here's where you will add some code to rollback on failure 
       - revert-migrations
       - destroy-environment 
+
+  smoke-test:
+    docker:
+      # Lightweight Docker image 
+      - image: python:3.10.4
+    steps:
+      # Checkout code from git
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
+            pip install pip --upgrade
+            pip install awscli
+            apk add --update curl nodejs npm
+      - run:
+          name: Get backend url
+          command: |
+            # your code here
+            touch ".env"
+            export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+            echo $BACKEND_IP
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "API_URL = ${API_URL}"
+            #echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+            #cat frontend/.env
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+              return 0
+            else
+              return 1
+            fi
+      - run:
+          name: Backend smoke test.
+          command: |
+            # your code here
+            curl "${API_URL}/api/status"
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+              return 0
+            else
+              return 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            # your code here
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.eu-central-1.amazonaws.com/#/employees"            
+            curl -s http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.eu-central-1.amazonaws.com/#/employees | grep "Welcome"
+            echo ${URL} 
+            if curl -s http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.eu-central-1.amazonaws.com/#/employees | grep "Welcome"
+            then
+                # Change this to 0 after the job fails
+              return 0
+            else
+              return 1
+            fi
+      # Here's where you will add some code to rollback on failure  
+      - revert-migrations
+      - destroy-environment
+
 
 workflows:
   default:
