Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -403,36 +403,47 @@ jobs:
             echo "API_URL = ${API_URL}"
             #echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
             #cat frontend/.env
-            if curl "${API_URL}/api/status" | grep "ok"
+      - run:
+          name: Backend smoke test.
+          command: |
+            # your code here
+            #curl "${API_URL}/api/status"
+            #if curl "${API_URL}/api/status" | grep "ok"
+            #then
+            #  exit 0
+            #else
+            #  exit 1
+            #fi
+            response=$(curl -s "${API_URL}/api/status")
+            echo $response
+            if echo $response | grep "ok"
             then
               exit 0
             else
               exit 1
             fi
       - run:
-          name: Backend smoke test.
-          command: |
-            # your code here
-            curl "${API_URL}/api/status"
-            if curl "${API_URL}/api/status" | grep "ok"
-            then
-              return 0
-            else
-              return 1
-            fi
-      - run:
           name: Frontend smoke test.
           command: |
             # your code here
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.eu-central-1.amazonaws.com/#/employees"            
-            curl -s http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.eu-central-1.amazonaws.com/#/employees | grep "Welcome"
-            echo ${URL} 
-            if curl -s http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.eu-central-1.amazonaws.com/#/employees | grep "Welcome"
+            #URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.eu-central-1.amazonaws.com/#/employees"            
+            #curl -s http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.eu-central-1.amazonaws.com/#/employees | grep "Welcome"
+            #echo ${URL} 
+            #if curl -s http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.eu-central-1.amazonaws.com/#/employees | grep "Welcome"
+            #then
+            #    # Change this to 0 after the job fails
+            #  exit 0
+            #else
+            #  exit 1
+            #fi
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.eu-central-1.amazonaws.com/#/employees"
+            response=$(curl -s http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.eu-central-1.amazonaws.com/#/employees)
+            echo $response
+            if echo $response | grep "Welcome"
             then
-                # Change this to 0 after the job fails
-              return 0
+              exit 0
             else
-              return 1
+              exit 1
             fi
       # Here's where you will add some code to rollback on failure  
       - revert-migrations
